In [1]:
!pip install -q yfinance

In [4]:
import yfinance as yf

df = yf.download(
    "GC=F",
    start="2000-01-01",
    end="2026-08-06",
    interval="1d"
)

df.columns = df.columns.droplevel(1)
df.columns.name = None

df.shape

/tmp/ipykernel_628/2709396958.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(
[*********************100%***********************]  1 of 1 completed

(6506, 5)

In [5]:
# تحويل سعر الأونصة إلى سعر الجرام (عيار 24)
df["24K"] = df["Close"] / 31.1035

# حساب بقية العيارات
df["22K"] = df["24K"] * (22/24)
df["21K"] = df["24K"] * (21/24)
df["18K"] = df["24K"] * (18/24)

In [6]:
print(df.tail())

                  Close         High          Low         Open  Volume  \
Date
2026-07-30  4100.100098  4118.500000  4028.500000  4060.699951   16985
2026-07-31  4049.100098  4102.399902  4022.399902  4102.399902    1166
2026-08-03  4033.699951  4083.500000  4026.500000  4083.399902     698
2026-08-04  4095.399902  4095.399902  4048.800049  4050.500000     698
2026-08-05  4304.500000  4325.500000  4121.600098  4133.799805  178268

                   24K         22K         21K         18K
Date
2026-07-30  131.821181  120.836082  115.343533   98.865886
2026-07-31  130.181494  119.333036  113.908807   97.636120
2026-08-03  129.686368  118.879171  113.475572   97.264776
2026-08-04  131.670066  120.697561  115.211308   98.752550
2026-08-05  138.392785  126.860053  121.093687  103.794589

In [7]:
df.iloc[0]

Close     273.899994
High      273.899994
Low       273.899994
Open      273.899994
Volume      0.000000
24K         8.806083
22K         8.072242
21K         7.705322
18K         6.604562
Name: 2000-08-30 00:00:00, dtype: float64

In [8]:
df.head()

,Close,High,Low,Open,Volume,24K,22K,21K,18K
Date,,,,,,,,,
2000-08-30,273.899994,273.899994,273.899994,273.899994,0,8.806083,8.072242,7.705322,6.604562
2000-08-31,278.299988,278.299988,274.799988,274.799988,0,8.947546,8.201917,7.829102,6.710659
2000-09-01,277.000000,277.000000,277.000000,277.000000,0,8.905750,8.163604,7.792531,6.679313
2000-09-05,275.799988,275.799988,275.799988,275.799988,2,8.867169,8.128238,7.758773,6.650377
2000-09-06,274.200012,274.200012,274.200012,274.200012,0,8.815729,8.081084,7.713762,6.611796